version: "3"
services:
  client:
    image: "shionhartvtas/multi-client-10-14"
    mem_limit: 128m
    hostname: client
  server:
    image: "shionhartvtas/multi-server-10-14"
    mem_limit: 128m
    hostname: api
    environment:
      # - REDIS_HOST=$REDIS_HOST
      # - REDIS_PORT=$REDIS_PORT
      # - PGUSER=$PGUSER
      # - PGHOST=$PGHOST
      # - PGDATABASE=$PGDATABASE
      # - PGPASSWORD=$PGPASSWORD
      # - PGPORT=$PGPORT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  worker:
    image: "shionhartvtas/multi-worker-10-14"
    mem_limit: 128m
    hostname: worker
    environment:
      # - REDIS_HOST=$REDIS_HOST
      # - REDIS_PORT=$REDIS_PORT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "shionhartvtas/multi-nginx-10-14"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
