FROM node:14-alpine3.11

WORKDIR '/app'

# Install dependencies within package.json
COPY package.json .
RUN npm config set strict-ssl false
RUN npm install

# May not need this due to docker-compose but still worth having
COPY . .

# Start the application (start command in package.json)
CMD ["npm", "run", "dev"]
